godot_version = "4.5.0"

[asset_definitions.1822]
id = "1822"
title = "Phantom Camera"
source = "AssetLib"

[asset_definitions.2696]
id = "2696"
title = "Log.gd, a GDScript pretty-printer"
source = "AssetLib"

[asset_definitions.3338]
id = "3338"
title = "LimboConsole: in-game dev console"
source = "AssetLib"

[asset_definitions.3787]
id = "3787"
title = "LimboAI: Behavior Trees & State Machines (Godot 4.4)"
source = "AssetLib"

[asset_definitions."nilsiker/TileMapDual:fix/66-terraindual-terrains-array-assignment"]
id = "nilsiker/TileMapDual:fix/66-terraindual-terrains-array-assignment"
title = "nilsiker.TileMapDual"
source = "Git"

[install_folders]
1572 = "AsepriteWizard"
1822 = "phantom_camera"
2696 = "log"
3338 = "limbo_console"
3787 = "limboai"
"nilsiker/TileMapDual:fix/66-terraindual-terrains-array-assignment" = "TileMapDual"
